agent_id: gcp.loadbalancer_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on GCP.LoadBalancer.
capability:
  analysis_window_days: 30
  optional_metrics: []
  required_metrics: []
  service: GCP.LoadBalancer
  supported_recommendation_types:
  - rightsizing
  thresholds: {}
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: GCP.LoadBalancer
service_specific_prompt: Analyze GCP.LoadBalancer resources for cost optimization
  opportunities.
temperature: 0.1
