agent_id: aws.lambda_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on Lambda
  functions.
capability:
  analysis_window_days: 30
  optional_metrics:
  - errors
  - throttles
  required_metrics:
  - invocation_count
  - duration_avg
  - memory_used
  service: AWS.Lambda
  supported_recommendation_types:
  - rightsizing
  thresholds:
    duration_efficiency_threshold: 80.0
    memory_utilization_threshold: 60.0
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: AWS.Lambda
service_specific_prompt: '
  Analyze Lambda functions for cost optimization opportunities. Consider:
  1. Memory allocation vs actual usage
  2. Execution duration patterns
  3. Invocation frequency and patterns
  4. Cold start optimization
  5. Cost per invocation analysis
  Provide specific recommendations with memory settings and architectural improvements.
  '
temperature: 0.1
