agent_id: aws.natgateway_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on AWS.NATGateway.
capability:
  analysis_window_days: 30
  optional_metrics: []
  required_metrics: []
  service: AWS.NATGateway
  supported_recommendation_types:
  - rightsizing
  thresholds: {}
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: AWS.NATGateway
service_specific_prompt: Analyze AWS.NATGateway resources for cost optimization opportunities.
temperature: 0.1
