agent_id: aws.rds_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on RDS databases.
capability:
  analysis_window_days: 30
  optional_metrics:
  - read_iops
  - write_iops
  - network_throughput
  required_metrics:
  - cpu_utilization_p50
  - cpu_utilization_p95
  - memory_utilization_p50
  service: AWS.RDS
  supported_recommendation_types:
  - rightsizing
  - purchasing_option
  - storage_class
  thresholds:
    cpu_low_threshold: 20.0
    iops_utilization_threshold: 20.0
    memory_low_threshold: 30.0
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: AWS.RDS
service_specific_prompt: '
  Analyze RDS instances for cost optimization opportunities. Consider:
  1. CPU, memory, and IOPS utilization patterns
  2. Instance class optimization
  3. Purchase options (On-Demand vs Reserved)
  4. Storage type optimization (GP2 vs GP3 vs Provisioned IOPS)
  5. Multi-AZ vs Single-AZ based on requirements
  Provide specific recommendations with instance classes and cost calculations.
  '
temperature: 0.1
