# Demo configuration with fallback enabled for testing without AWS credentials
enabled: true
default_currency: "USD"
default_region: "us-east-1"

# API Configuration
aws_pricing_api_region: "us-east-1"
enable_pricing_cache: true
cache_duration_hours: 24

# Rate Limiting
api_rate_limit_per_second: 10
max_concurrent_requests: 50

# Fallback Pricing - Enable for demo
enable_fallback_pricing: true
fallback_pricing_file: "aws_fallback_pricing.yaml"

# Force fallback mode for demo (skip API calls)
force_fallback_mode: true

# Logging
log_pricing_queries: true
log_cache_hits: false
