# AWS Pricing Service Configuration
# This file controls global pricing behavior

enabled: true
default_currency: "USD"
default_region: "us-east-1"

# API Configuration
aws_pricing_api_region: "us-east-1"
enable_pricing_cache: true
cache_duration_hours: 24

# Rate Limiting
api_rate_limit_per_second: 10
max_concurrent_requests: 50

# Fallback Pricing
enable_fallback_pricing: true
fallback_pricing_file: "aws_fallback_pricing.yaml"

# Logging
log_pricing_queries: true
log_cache_hits: false
