# Static EC2 pricing for demo purposes
# Format: "region:instance_type": {"on_demand": price, "unit": "hour"}

# US East 1 (N. Virginia)
"us-east-1:t3.nano":
  on_demand: 0.0052
  unit: "hour"

"us-east-1:t3.micro":
  on_demand: 0.0104
  unit: "hour"

"us-east-1:t3.small":
  on_demand: 0.0208
  unit: "hour"

"us-east-1:t3.medium":
  on_demand: 0.0416
  unit: "hour"

"us-east-1:t3.large":
  on_demand: 0.0832
  unit: "hour"

"us-east-1:t3.xlarge":
  on_demand: 0.1664
  unit: "hour"

"us-east-1:t3.2xlarge":
  on_demand: 0.3328
  unit: "hour"

"us-east-1:m5.large":
  on_demand: 0.096
  unit: "hour"

"us-east-1:m5.xlarge":
  on_demand: 0.192
  unit: "hour"

"us-east-1:m5.2xlarge":
  on_demand: 0.384
  unit: "hour"

"us-east-1:c5.large":
  on_demand: 0.085
  unit: "hour"

"us-east-1:c5.xlarge":
  on_demand: 0.17
  unit: "hour"

"us-east-1:r5.large":
  on_demand: 0.126
  unit: "hour"

"us-east-1:r5.xlarge":
  on_demand: 0.252
  unit: "hour"

# US West 2 (Oregon) - typically same as us-east-1
"us-west-2:t3.medium":
  on_demand: 0.0416
  unit: "hour"

"us-west-2:m5.large":
  on_demand: 0.096
  unit: "hour"

# EU West 1 (Ireland)
"eu-west-1:t3.medium":
  on_demand: 0.0464
  unit: "hour"

"eu-west-1:m5.large":
  on_demand: 0.107
  unit: "hour"
