# AWS EC2 Pricing Rule Configuration
service_type: "AWS.EC2"
cloud_provider: "AWS"

# API Configuration
api_endpoint: "pricing.us-east-1.amazonaws.com"
calculation_method: "aws_pricing_api"

# AWS Pricing API Filters
api_filters:
  service_code: "AmazonEC2"
  filters:
    - type: "TERM_MATCH"
      field: "servicecode"
      value: "AmazonEC2"
    - type: "TERM_MATCH"
      field: "location"
      value: "${region}"
    - type: "TERM_MATCH"
      field: "instanceType"
      value: "${instance_type}"
    - type: "TERM_MATCH"
      field: "operating-system"
      value: "Linux"
    - type: "TERM_MATCH"
      field: "tenancy"
      value: "Shared"
    - type: "TERM_MATCH"
      field: "preInstalledSw"
      value: "NA"

# Price Dimensions to Extract
price_dimensions:
  - "OnDemand"
  - "Reserved"

# Caching
cache_duration_hours: 24
enable_fallback: true
fallback_multiplier: 1.1

# Regional Pricing Mappings
region_mappings:
  "us-east-1": "US East (N. Virginia)"
  "us-west-2": "US West (Oregon)"
  "eu-west-1": "Europe (Ireland)"
  "ap-southeast-1": "Asia Pacific (Singapore)"

# Attributes for fallback pricing calculation
attributes:
  pricing_formula:
    base_price: 0.005
    vcpu_multiplier: 0.02
    memory_multiplier: 0.01
  
  # Common instance families and their base multipliers
  instance_family_multipliers:
    "t3": 1.0      # Burstable baseline
    "t4g": 0.8     # ARM-based discount
    "m5": 1.2      # General purpose
    "c5": 1.3      # Compute optimized
    "r5": 1.8      # Memory optimized
    "x1": 3.0      # High memory
    "i3": 2.0      # Storage optimized
    "p3": 15.0     # GPU instances
    
  # Reserved Instance configurations
  reserved_instances:
    - term: "1_year"
      payment_options:
        - "no_upfront"
        - "partial_upfront" 
        - "all_upfront"
      discount_percentage: 0.3
    - term: "3_year"
      payment_options:
        - "no_upfront"
        - "partial_upfront"
        - "all_upfront"
      discount_percentage: 0.5
