# AWS Fallback Pricing - Used when API calls fail
# Prices in USD per hour unless otherwise specified

# EC2 Instance Pricing (per hour)
ec2:
  us-east-1:
    t3.nano: 0.0052
    t3.micro: 0.0104
    t3.small: 0.0208
    t3.medium: 0.0416
    t3.large: 0.0832
    t3.xlarge: 0.1664
    t3.2xlarge: 0.3328
    m5.large: 0.096
    m5.xlarge: 0.192
    m5.2xlarge: 0.384
    m5.4xlarge: 0.768
    c5.large: 0.085
    c5.xlarge: 0.17
    c5.2xlarge: 0.34
    r5.large: 0.126
    r5.xlarge: 0.252
    r5.2xlarge: 0.504

  us-west-2:
    t3.nano: 0.0052
    t3.micro: 0.0104
    t3.small: 0.0208
    t3.medium: 0.0416
    t3.large: 0.0832
    m5.large: 0.096
    m5.xlarge: 0.192
    c5.large: 0.085
    r5.large: 0.126

# RDS Instance Pricing (per hour)
rds:
  us-east-1:
    db.t3.micro: 0.017
    db.t3.small: 0.034
    db.t3.medium: 0.068
    db.t3.large: 0.136
    db.m5.large: 0.192
    db.m5.xlarge: 0.384
    db.r5.large: 0.24
    db.r5.xlarge: 0.48

# EBS Storage Pricing (per GB-month)
ebs:
  us-east-1:
    gp2: 0.10
    gp3: 0.08
    io1: 0.125
    io2: 0.125
    st1: 0.045
    sc1: 0.025

# S3 Storage Pricing (per GB-month)
s3:
  us-east-1:
    STANDARD: 0.023
    STANDARD_IA: 0.0125
    ONEZONE_IA: 0.01
    GLACIER: 0.004
    DEEP_ARCHIVE: 0.00099

# Lambda Pricing
lambda:
  us-east-1:
    request_price_per_million: 0.20
    gb_second_price: 0.0000166667
    provisioned_concurrency_per_hour_per_gb: 0.000004167

# Load Balancer Pricing (per hour)
load_balancer:
  us-east-1:
    alb: 0.0225
    nlb: 0.0225
    gwlb: 0.0125
    classic: 0.025

# NAT Gateway Pricing (per hour + per GB processed)
nat_gateway:
  us-east-1:
    hourly_rate: 0.045
    data_processing_per_gb: 0.045

# CloudFront Pricing (per GB)
cloudfront:
  global:
    first_10tb: 0.085
    next_40tb: 0.080
    next_100tb: 0.060
    next_350tb: 0.040
    over_500tb: 0.030

# ElasticIP Pricing (per hour when not associated)
elastic_ip:
  us-east-1:
    unassociated_hourly: 0.005
