# AWS Lambda Pricing Rule Configuration
service_type: "AWS.Lambda"
cloud_provider: "AWS"

# API Configuration
api_endpoint: "pricing.us-east-1.amazonaws.com"
calculation_method: "static_lookup"  # Lambda has simpler, more predictable pricing

# AWS Pricing API Filters (for reference, but using static_lookup)
api_filters:
  service_code: "AWSLambda"
  filters:
    - type: "TERM_MATCH"
      field: "servicecode"
      value: "AWSLambda"
    - type: "TERM_MATCH"
      field: "location"
      value: "${region}"

# Price Dimensions to Extract
price_dimensions:
  - "OnDemand"

# Caching
cache_duration_hours: 168  # 1 week (Lambda pricing rarely changes)
enable_fallback: true
fallback_multiplier: 1.02

# Regional Pricing Mappings
region_mappings:
  "us-east-1": "US East (N. Virginia)"
  "us-west-2": "US West (Oregon)"
  "eu-west-1": "Europe (Ireland)"
  "ap-southeast-1": "Asia Pacific (Singapore)"

# Attributes for Lambda pricing calculation
attributes:
  static_pricing_file: "aws_lambda_static_pricing.yaml"
  
  # Request pricing (per million requests)
  request_pricing:
    standard: 0.20  # $0.20 per 1M requests
    provisioned_concurrency: 0.20  # Same as standard
  
  # Compute pricing (per GB-second)
  compute_pricing:
    x86_64:
      price_per_gb_second: 0.0000166667  # $0.0000166667 per GB-second
      free_tier_gb_seconds: 400000  # 400,000 GB-seconds per month
    arm64:
      price_per_gb_second: 0.0000133334  # 20% discount for Graviton2
      free_tier_gb_seconds: 400000

  # Memory configurations and their pricing impact
  memory_tiers:
    128: 0.125   # 128 MB = 0.125 GB
    256: 0.25    # 256 MB = 0.25 GB
    512: 0.5     # 512 MB = 0.5 GB
    1024: 1.0    # 1024 MB = 1 GB
    1536: 1.5    # 1536 MB = 1.5 GB
    2048: 2.0    # 2048 MB = 2 GB
    3008: 3.008  # 3008 MB = 3.008 GB (max for x86)
    10240: 10.24 # 10240 MB = 10.24 GB (max for arm64)

  # Provisioned concurrency pricing (per hour per configured concurrency)
  provisioned_concurrency:
    price_per_hour_per_concurrency: 0.000004167  # $0.000004167 per hour per GB

  # Free tier allowances (monthly)
  free_tier:
    requests: 1000000      # 1M requests per month
    compute_gb_seconds: 400000  # 400K GB-seconds per month
    always_free: true      # Lambda free tier doesn't expire

  # Duration billing
  billing_increment_ms: 1  # Lambda bills in 1ms increments (since Dec 2020)
  
  # Common optimization recommendations
  optimization_thresholds:
    memory_utilization_low: 0.6   # < 60% memory usage suggests over-provisioning
    duration_high_ms: 15000       # > 15s suggests architecture issues
    cold_start_threshold_ms: 1000 # Cold starts > 1s impact user experience
    
  # Cost calculation helpers
  seconds_per_month: 2592000  # 30 days * 24 hours * 60 minutes * 60 seconds
  
  # Regional multipliers (some regions have different pricing)
  regional_multipliers:
    "us-east-1": 1.0      # Baseline
    "us-west-2": 1.0      # Same as us-east-1
    "eu-west-1": 1.0      # Same as us-east-1
    "ap-southeast-1": 1.1 # Slightly higher
    "ap-northeast-1": 1.1 # Slightly higher
    "sa-east-1": 1.2      # Higher for South America
