# AWS Lambda Static Pricing
# Lambda pricing is consistent across most regions with minor variations

# Request pricing (per million requests)
request_pricing:
  us-east-1: 0.20
  us-west-2: 0.20
  eu-west-1: 0.20
  ap-southeast-1: 0.22
  ap-northeast-1: 0.22

# Compute pricing (per GB-second)
compute_pricing:
  x86_64:
    us-east-1: 0.0000166667
    us-west-2: 0.0000166667
    eu-west-1: 0.0000166667
    ap-southeast-1: 0.0000183334
    ap-northeast-1: 0.0000183334
  
  arm64:
    us-east-1: 0.0000133334
    us-west-2: 0.0000133334
    eu-west-1: 0.0000133334
    ap-southeast-1: 0.0000146667
    ap-northeast-1: 0.0000146667

# Provisioned concurrency pricing (per hour per GB of configured concurrency)
provisioned_concurrency:
  us-east-1: 0.000004167
  us-west-2: 0.000004167
  eu-west-1: 0.000004167
  ap-southeast-1: 0.000004584
  ap-northeast-1: 0.000004584

# Free tier (monthly limits)
free_tier:
  requests: 1000000
  gb_seconds: 400000
  provisioned_concurrency_gb_hours: 0  # No free tier for provisioned concurrency
