# AWS RDS Pricing Rule Configuration
service_type: "AWS.RDS"
cloud_provider: "AWS"

# API Configuration
api_endpoint: "pricing.us-east-1.amazonaws.com"
calculation_method: "aws_pricing_api"

# AWS Pricing API Filters
api_filters:
  service_code: "AmazonRDS"
  filters:
    - type: "TERM_MATCH"
      field: "servicecode"
      value: "AmazonRDS"
    - type: "TERM_MATCH"
      field: "location"
      value: "${region}"
    - type: "TERM_MATCH"
      field: "instanceType"
      value: "${instance_type}"
    - type: "TERM_MATCH"
      field: "databaseEngine"
      value: "${engine}"
    - type: "TERM_MATCH"
      field: "deploymentOption"
      value: "${deployment_option}"

# Price Dimensions to Extract
price_dimensions:
  - "OnDemand"
  - "Reserved"

# Caching
cache_duration_hours: 24
enable_fallback: true
fallback_multiplier: 1.15

# Regional Pricing Mappings
region_mappings:
  "us-east-1": "US East (N. Virginia)"
  "us-west-2": "US West (Oregon)"
  "eu-west-1": "Europe (Ireland)"
  "ap-southeast-1": "Asia Pacific (Singapore)"

# Attributes for RDS pricing calculation
attributes:
  # Database engines and their relative pricing
  engine_multipliers:
    "mysql": 1.0
    "postgres": 1.0
    "mariadb": 1.0
    "aurora": 1.4
    "aurora-mysql": 1.4
    "aurora-postgresql": 1.4
    "oracle-ee": 3.5
    "oracle-se2": 2.0
    "sqlserver-ee": 4.0
    "sqlserver-se": 2.5
    "sqlserver-ex": 1.0
    "sqlserver-web": 1.2

  # Deployment options
  deployment_options:
    "Single-AZ": 1.0
    "Multi-AZ": 2.0
    "Multi-AZ (SQL Server Mirror)": 2.0

  # Instance families and their base pricing
  instance_families:
    "db.t3": 
      base_price: 0.017
      vcpu_multiplier: 0.01
      memory_multiplier: 0.005
    "db.t4g":
      base_price: 0.013  # ARM-based discount
      vcpu_multiplier: 0.008
      memory_multiplier: 0.004
    "db.m5":
      base_price: 0.088
      vcpu_multiplier: 0.02
      memory_multiplier: 0.01
    "db.r5":
      base_price: 0.126
      vcpu_multiplier: 0.03
      memory_multiplier: 0.008
    "db.x1e":
      base_price: 0.668
      vcpu_multiplier: 0.15
      memory_multiplier: 0.003

  # Storage pricing (per GB-month)
  storage_types:
    "gp2":
      base_price: 0.115
      iops_included: 3  # IOPS per GB
      max_iops: 16000
    "gp3":
      base_price: 0.115
      iops_included: 3000  # Base IOPS
      iops_price_per_unit: 0.20  # Per provisioned IOPS above 3000
      throughput_included: 125  # MB/s
      throughput_price_per_mbps: 0.16  # Per MB/s above 125
    "io1":
      base_price: 0.125
      iops_price_per_unit: 0.10  # Per provisioned IOPS
    "io2":
      base_price: 0.125
      iops_price_per_unit: 0.065  # Per provisioned IOPS (cheaper than io1)

  # Backup storage pricing
  backup_storage:
    included_percentage: 100  # 100% of allocated storage is free
    additional_per_gb: 0.095

  # Reserved Instance configurations
  reserved_instances:
    - term: "1_year"
      payment_options:
        - "no_upfront"
        - "partial_upfront" 
        - "all_upfront"
      discount_percentage: 0.38
    - term: "3_year"
      payment_options:
        - "no_upfront"
        - "partial_upfront"
        - "all_upfront"
      discount_percentage: 0.60

  # Data transfer pricing
  data_transfer:
    backup_to_s3: 0.0  # Free
    cross_az: 0.01     # Per GB
    cross_region: 0.02  # Per GB
