# AWS S3 Pricing Rule Configuration
service_type: "AWS.S3"
cloud_provider: "AWS"

# API Configuration
api_endpoint: "pricing.us-east-1.amazonaws.com"
calculation_method: "aws_pricing_api"

# AWS Pricing API Filters
api_filters:
  service_code: "AmazonS3"
  filters:
    - type: "TERM_MATCH"
      field: "servicecode"
      value: "AmazonS3"
    - type: "TERM_MATCH"
      field: "location"
      value: "${region}"
    - type: "TERM_MATCH"
      field: "storageClass"
      value: "${storage_class}"
    - type: "TERM_MATCH"
      field: "volumeType"
      value: "Standard"

# Price Dimensions to Extract
price_dimensions:
  - "OnDemand"

# Caching
cache_duration_hours: 168  # 1 week (S3 pricing changes less frequently)
enable_fallback: true
fallback_multiplier: 1.05

# Regional Pricing Mappings
region_mappings:
  "us-east-1": "US East (N. Virginia)"
  "us-west-2": "US West (Oregon)"
  "eu-west-1": "Europe (Ireland)"
  "ap-southeast-1": "Asia Pacific (Singapore)"

# Attributes for S3 pricing calculation
attributes:
  # Storage class pricing (per GB-month)
  storage_classes:
    "STANDARD":
      base_price: 0.023
      request_pricing:
        PUT: 0.0004  # per 1,000 requests
        GET: 0.0004  # per 1,000 requests
    "STANDARD_IA":
      base_price: 0.0125
      minimum_storage_duration_days: 30
      retrieval_fee_per_gb: 0.01
      request_pricing:
        PUT: 0.001
        GET: 0.001
    "ONEZONE_IA":
      base_price: 0.01
      minimum_storage_duration_days: 30
      retrieval_fee_per_gb: 0.01
      request_pricing:
        PUT: 0.001
        GET: 0.001
    "GLACIER":
      base_price: 0.004
      minimum_storage_duration_days: 90
      retrieval_fee_per_gb: 0.03
      request_pricing:
        PUT: 0.03
        retrieval: 0.0004
    "GLACIER_IR":
      base_price: 0.0036
      minimum_storage_duration_days: 90
      retrieval_fee_per_gb: 0.03
      request_pricing:
        PUT: 0.03
        retrieval: 0.0004
    "DEEP_ARCHIVE":
      base_price: 0.00099
      minimum_storage_duration_days: 180
      retrieval_fee_per_gb: 0.0025
      request_pricing:
        PUT: 0.05
        retrieval: 0.0004

  # Data transfer pricing (per GB)
  data_transfer:
    internet_egress:
      first_gb_free: 1
      up_to_10tb: 0.09
      next_40tb: 0.085
      next_100tb: 0.07
      over_150tb: 0.05
    
    cloudfront_egress: 0.0  # Free to CloudFront
    
    cross_region_replication:
      base_rate: 0.02
      
  # Request pricing varies by operation type
  request_types:
    - "PUT"
    - "COPY" 
    - "POST"
    - "LIST"
    - "GET"
    - "SELECT"
    - "Lifecycle"
