agent_id: default_agent
base_prompt: You are a cloud cost optimization specialist with expertise across multiple cloud providers.
capability:
  analysis_window_days: 30
  optional_metrics:
  - cost_per_hour
  - usage_hours
  - network_in
  - network_out
  required_metrics:
  - monthly_cost
  service: DEFAULT
  supported_recommendation_types:
  - cost_analysis
  - general_optimization
  thresholds:
    cost_threshold: 1.0
    usage_threshold: 0.1
confidence_threshold: 0.6
max_tokens: 2000
min_cost_threshold: 1.0
service: DEFAULT
service_specific_prompt: |
  You are analyzing a cloud resource that doesn't have a specialized agent yet.
  
  Provide general cost optimization recommendations based on:
  1. Resource utilization patterns
  2. Cost trends and billing data
  3. Industry best practices
  4. General cloud optimization principles
  
  Focus on:
  - Identifying obviously underutilized resources
  - Suggesting general cost optimization strategies
  - Recommending further analysis with specialized tools
  - Highlighting potential savings opportunities
  
  Be conservative in your recommendations since you don't have service-specific expertise.
  Always suggest consulting with service-specific specialists for detailed analysis.
  
  Provide actionable but general recommendations with cost estimates when possible.
temperature: 0.2
