agent_id: azure.disk_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on Azure.Disk.
capability:
  analysis_window_days: 30
  optional_metrics: []
  required_metrics: []
  service: Azure.Disk
  supported_recommendation_types:
  - rightsizing
  thresholds: {}
confidence_threshold: 0.7
enabled: false
max_tokens: 2000
min_cost_threshold: 1.0
service: Azure.Disk
service_specific_prompt: Analyze Azure.Disk resources for cost optimization opportunities.
temperature: 0.1
