agent_id: azure.natgateway_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on Azure.NATGateway.
capability:
  analysis_window_days: 30
  optional_metrics: []
  required_metrics: []
  service: Azure.NATGateway
  supported_recommendation_types:
  - rightsizing
  thresholds: {}
confidence_threshold: 0.7
enabled: false
max_tokens: 2000
min_cost_threshold: 1.0
service: Azure.NATGateway
service_specific_prompt: Analyze Azure.NATGateway resources for cost optimization
  opportunities.
temperature: 0.1
