confidence_weight: 0.2
enabled_services:
- AWS.EC2
- AWS.EBS
- AWS.S3
- AWS.EFS
- AWS.RDS
- AWS.RDS_SNAPSHOTS
- AWS.DynamoDB
- AWS.Lambda
- AWS.CloudFront
- AWS.ALB
- AWS.NLB
- AWS.GWLB
- AWS.ElasticIP
- AWS.NATGateway
- AWS.VPCEndpoints
- AWS.SQS
- AWS.SNS
implementation_ease_weight: 0.1
include_low_impact: false
max_recommendations_per_service: 50
risk_weight: 0.3
savings_weight: 0.4
similarity_threshold: 0.8
