agent_id: ec2_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on EC2 instances.
capability:
  analysis_window_days: 30
  optional_metrics:
  - network_in
  - network_out
  required_metrics:
  - cpu_utilization_p50
  - cpu_utilization_p95
  - memory_utilization_p50
  service: EC2
  supported_recommendation_types:
  - rightsizing
  - purchasing_option
  - idle_resource
  thresholds:
    cpu_idle_threshold: 5.0
    cpu_low_threshold: 20.0
    memory_low_threshold: 30.0
    uptime_threshold: 0.95
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: EC2
service_specific_prompt: '

  Analyze EC2 instances for cost optimization opportunities. Consider:

  1. CPU and memory utilization patterns

  2. Instance family and generation efficiency

  3. Purchase options (On-Demand vs Reserved vs Spot)

  4. Idle or underutilized instances

  5. Right-sizing opportunities based on actual usage


  Provide specific recommendations with exact instance types and cost calculations.

  '
temperature: 0.1
