agent_id: elasticip_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on ElasticIP.
capability:
  analysis_window_days: 30
  optional_metrics: []
  required_metrics: []
  service: AWS.ElasticIP
  supported_recommendation_types:
  - idle_resource
  thresholds: {}
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: AWS.ElasticIP

# Custom conditional rules for ElasticIP optimization
custom_rules:
  # Unattached Elastic IPs immediate cleanup
  - name: "unattached_eip_cleanup"
    description: "Unattached Elastic IPs incur unnecessary charges"
    enabled: true
    priority: 100
    logic: "AND"
    conditions:
      - field: "property.status"
        operator: "equals"
        value: "available"
        description: "EIP is not attached to any instance"
    force_recommendation_types:
      - "idle_resource"
    custom_prompt: "This Elastic IP is unattached and incurring unnecessary charges ($3.65/month). Unless reserved for specific use, it should be released immediately to eliminate ongoing costs."
    
  # Production EIPs need careful review
  - name: "production_eip_review"
    description: "Production EIPs need careful review before cleanup"
    enabled: true
    priority: 90
    logic: "AND"
    conditions:
      - field: "tag.Environment"
        operator: "equals"
        value: "production"
        description: "Production environment EIP"
      - field: "property.status"
        operator: "equals"
        value: "available"
        description: "EIP is not attached"
    risk_adjustment: "increase"
    custom_prompt: "This is a production Elastic IP that is currently unattached. Verify with the team if this IP is reserved for specific use before recommending release. Consider if it's needed for disaster recovery or maintenance procedures."

service_specific_prompt: 'Analyze Elastic IP addresses for cost optimization opportunities. Consider:
  1. Unattached Elastic IPs that incur charges
  2. IPs reserved but not currently in use
  3. Environment-specific retention policies
  4. Business requirements for static IP addresses
  
  Provide specific recommendations for cost reduction while maintaining operational requirements.'
temperature: 0.1
