agent_id: s3_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on S3 storage.
capability:
  analysis_window_days: 90
  optional_metrics:
  - data_retrieval
  - data_transfer
  required_metrics:
  - storage_used
  - requests_get
  - requests_put
  service: S3
  supported_recommendation_types:
  - storage_class
  - lifecycle
  thresholds:
    deep_archive_threshold: 180
    glacier_access_threshold: 90
    ia_access_threshold: 30
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: S3

# Custom conditional rules for S3 optimization
custom_rules:
  # Compliance buckets need special handling
  - name: "compliance_retention_rules"
    description: "Compliance buckets have specific retention and access requirements"
    enabled: true
    priority: 100
    logic: "OR"
    conditions:
      - field: "tag.Compliance"
        operator: "equals"
        value: "SOX"
        description: "SOX compliance bucket"
      - field: "tag.DataClass"
        operator: "in"
        value: ["PII", "PHI", "financial"]
        description: "Sensitive data classification"
      - field: "property.bucket_name"
        operator: "contains"
        value: "compliance"
        description: "Compliance in bucket name"
    threshold_overrides:
      ia_access_threshold: 90  # Longer retention in Standard
      glacier_access_threshold: 365  # One year before Glacier
    custom_prompt: "This bucket contains compliance-sensitive data. Ensure lifecycle policies meet regulatory retention requirements and provide audit trail considerations."
    
  # Log buckets for aggressive archival
  - name: "log_aggressive_archival"
    description: "Log buckets can be archived aggressively"
    enabled: true
    priority: 80
    logic: "OR"
    conditions:
      - field: "tag.DataType"
        operator: "equals"
        value: "logs"
        description: "Log data bucket"
      - field: "property.bucket_name"
        operator: "regex"
        value: "(log|audit|access|cloudtrail)"
        description: "Log-related bucket names"
    threshold_overrides:
      ia_access_threshold: 7   # Quick transition to IA
      glacier_access_threshold: 30  # Archive logs quickly
      deep_archive_threshold: 90
    force_recommendation_types:
      - "lifecycle"
    custom_prompt: "This appears to be a log storage bucket. Implement aggressive lifecycle policies to minimize storage costs while maintaining compliance requirements."
    
  # Backup buckets special handling
  - name: "backup_long_term_strategy"
    description: "Backup buckets need long-term retention strategy"
    enabled: true
    priority: 75
    logic: "OR"
    conditions:
      - field: "tag.Purpose"
        operator: "equals"
        value: "backup"
        description: "Backup purpose bucket"
      - field: "property.bucket_name"
        operator: "contains"
        value: "backup"
        description: "Backup in bucket name"
    threshold_overrides:
      ia_access_threshold: 30
      glacier_access_threshold: 90
      deep_archive_threshold: 365  # Long-term retention
    custom_prompt: "This is a backup storage bucket. Focus on long-term cost optimization with appropriate retrieval time considerations for disaster recovery scenarios."
    
  # High-access buckets avoid archival
  - name: "high_access_no_archival"
    description: "High-access buckets should avoid archival storage classes"
    enabled: true
    priority: 85
    logic: "AND"
    conditions:
      - field: "requests_get"
        operator: "greater_than"
        value: 10000  # High GET requests
        description: "High access patterns"
      - field: "tag.AccessPattern"
        operator: "in"
        value: ["frequent", "real-time", "hot"]
        description: "Frequent access tags"
    skip_recommendation_types:
      - "lifecycle"
    custom_prompt: "This bucket has high access patterns. Focus on Standard storage optimizations and avoid lifecycle policies that could impact access performance."
    
  # Large buckets priority optimization
  - name: "large_bucket_priority"
    description: "Large buckets should be prioritized for optimization"
    enabled: true
    priority: 90
    logic: "AND"
    conditions:
      - field: "storage_used"
        operator: "greater_than"
        value: 1000000000000  # 1TB in bytes
        description: "Large storage bucket (>1TB)"
    force_recommendation_types:
      - "lifecycle"
      - "storage_class"
    custom_prompt: "This is a large storage bucket (>1TB). Even small percentage savings will have significant impact. Provide detailed analysis of lifecycle policies and storage class optimizations."

service_specific_prompt: '

  Analyze S3 buckets for cost optimization opportunities. Consider:

  1. Storage class optimization (Standard -> IA -> Glacier -> Deep Archive)

  2. Lifecycle policies for automatic transitions

  3. Access patterns and retrieval costs

  4. Incomplete multipart uploads

  5. Duplicate or redundant data


  Provide specific recommendations with storage classes and lifecycle rules.

  '
temperature: 0.1
