agent_id: azure.functions_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on Azure.Functions.
capability:
  analysis_window_days: 30
  optional_metrics: []
  required_metrics: []
  service: Azure.Functions
  supported_recommendation_types:
  - rightsizing
  thresholds: {}
confidence_threshold: 0.7
enabled: false
max_tokens: 2000
min_cost_threshold: 1.0
service: Azure.Functions
service_specific_prompt: Analyze Azure.Functions resources for cost optimization opportunities.
temperature: 0.1
