agent_id: azure.storage_agent
base_prompt: You are an expert AWS cost optimization specialist focusing on Azure.Storage.
capability:
  analysis_window_days: 30
  optional_metrics: []
  required_metrics: []
  service: Azure.Storage
  supported_recommendation_types:
  - rightsizing
  thresholds: {}
confidence_threshold: 0.7
enabled: true
max_tokens: 2000
min_cost_threshold: 1.0
service: Azure.Storage
service_specific_prompt: Analyze Azure.Storage resources for cost optimization opportunities.
temperature: 0.1
